export const eachPanel = {
	comp: {
		fullName: 'Complutensian Polyglot (Old Testament) – Open to Genesis 8',
		sources: [
			{
				id: 'cs1',
				type: 'Hebrew Text',
				category: 'sources',
				title: 'Making the Hebrew Text',
				subtitle: 'Scholars use medieval manuscripts to create the Hebrew text',
				image: 'VAULT folio Bonaparte 5022 no. 9 binding 1',
				src:['./resampled/bon_5022_no_09_binding_01.jpg', './resampled/bon_5022_no_09_binding_02.jpg'],
				metadata: '',
				creator: '',
				textTitle: 'First Chronicles in Hebrew',
				place: 'Spain',
				year: '11th century',
				narrative: 'All polyglot texts were ultimately based on manuscript copies of biblical texts. Thanks to its thriving Jewish community, Spain was the leading center of Hebrew scholarship since the Middle Ages. Everyone agreed that the highest quality Hebrew manuscripts were produced there, so Cisneros was well-positiond to acquire the best proof texts on which to base the Complutensian’s Hebrew edition, and the conversos recruited to produce it – Pablo Coronel, Alfonso de Toledo, and Alfonso de Zamora – all had extensive experience working with these manuscript sources. Even the later polyglots turned to Spanish manuscripts to produce their versions. The manuscript displayed above is the Newberry’s oldest Hebrew manuscript, a fragment of the Book of Chronicles that was made in Spain at some point in the 11th century.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=961738',
				otherAuthor: ['Ortega-Monasterio, Teresa. “Spanish Biblical Hebrew Manuscripts.” '],
				otherTitle: ['Hebrew Studies,'],
				otherBib: ['45 (2004), 163-74.'],
			},
			{
				id: 'cs2',
				type:'Vulgate',
				category: 'sources',
				title: 'The Vulgate',
				subtitle: 'The standard Latin translation of the Bible poses a challenge to polyglot scholars',
				image: 'Case MS 216 folio 005v',
				src:['./resampled/case_ms_216_folio_005v.jpg', './resampled/case_ms_216_folio_001r.jpg'],
				metadata: '',
				creator: '',
				textTitle: '[Bible][Manuscript]',
				place: 'France(?)',
				year: 'Ca. 1230-1250',
				narrative: 'Throughout the Middle Ages, the dominant version of the Bible was the Latin translation made in the 4th century that was attributed to St. Jerome. By the 16th century, scholars agreed that it was a very problematic text, filled with questionable translations and 1,000 years of inherited scribal errors that scholars were eager to fix. The Roman Church, however, considereed the Vulgate the definitive translation, and forbade anyone from making a corrected edition. As a result, the Complutensian scholars built their edition of the Vulgate from medieval manuscripts in Spain, none of which were complete. The Vulgate shown here a complete version of a 13th-century manuscript of the Vulgate from France.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=814053',
				otherAuthor: ['[Evangelistary] [manuscript]. Germany, between 1050 and 1100. VAULT folio Case MS 4'],
				otherTitle: [''],
				otherBib: [''],
			},
			{
				id: 'cs3',
				type: 'Targum Text',
				category: 'sources',
				title: 'Aramaic',
				subtitle: 'Scholars use medieval manuscripts to locate the first translation of the Old Testament',
				image: 'VAULT Hebrew MS 1, folio 6r-5r',
				src:['./resampled/hebrew_ms_001_folio_6r_5v.jpg', './resampled/hebrew_ms_01_folio_001r.jpg'], //?
				metadata: '',
				creator: ' ',
				textTitle: 'Targum Onkelos of the Pentateuch',
				place: 'Italy',
				year: '14th century',
				narrative: 'To represent as much of the divine mystery as possible, the Complutensian scholars decided to include the Targum, a paraphrase of the Hebrew Scriptures in Aramaic, the language that Jews spoke after classical Hebrew died out as a spoken vernacular. Manuscripts of it – such as this example from the Newberry’s collections – were widely used in Jewish synagogues throughout Europe to explain and interpret the Hebrew text. The Targum was both a translation and an explanation, incorporating commentary from generations of rabbis and even some Talmudic fables along with the text. This made it somewhat difficult to use as a source for a definitive text of the Bible, and the Complutensian only included the Targum for the first volume of the Bible (which contained the Pentateuch). Later polyglots would include the entire Targum, after more editorial work had been done.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=124482',
				otherAuthor: ['Münster, Sebastian.'],
				otherTitle: ['ʻArukh : dictionarium chaldaicum non ta[m] ad chaldaicos interpretes q[uam] rabbinoru[m] intelligenda co[m]mentaria necessarium.'],
				otherBib: ['Basel, 1527. VAULT Case PJ4937 .M86 1527'],
			},
			{
				id: 'cs4',
				type:'Septuagint Text (Greek)',
				category: 'sources',
				title: 'The Septuagint',
				subtitle: 'The Greek translation of the Old Testament gains new life in the polyglots',
				image: 'Folio Inc. 5966, f. something',
				src: [''], //inc_7763?
				metadata: '',
				creator: '',
				textTitle: '[Psalterium Graeco-Latinum cum canticis].',
				place: 'Milan, Italy',
				year: '1481',
				narrative: '[NEEDS IMAGES] Centuries before the birth of Christ, Greek-speaking Jews living in Egypt created a Greek translation of the Old Testament called the Septuagint, so-called because around 70 (Septuagint is the Latin word for 70) scholars produced it. During the Middle Ages, the Septuagint was relatively unknown in western Europe, where Jerome’s Vulgate translation dominated. Interest in learning and using Greek in religious studies grew throughout the 14th and 15th centuries, especially after the fall of Constantinople to the Ottoman Turks in 1453. Thereafter, Biblical material in Greek began to appear in print, beginning with the psalter pictured here. Inspired by this, Cisneros borrowed Septuagint manuscrips from the Vatican to produce the first printed edition of the entire Septuagint Old Testament in his polyglot.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=400646',
				otherAuthor: ['O’Connell, S.'],
				otherTitle: ['From Most Ancient Sources: The Nature and Text-Critical Use of the Greek Old Testament Text of the Complutensian Polyglot Bible.'],
				otherBib: ['Fribourg/Göttingen: Vandenhoeck and Ruprecht, 2006.'],

			},
			{
				id: 'cs5',
				type: 'Hebrew Text',
				category: 'sources',
				title: 'Making Hebrew Type',
				subtitle: 'Letter-founders create new typefaces for polyglots',
				image: 'Case Wing Z 40535 .156, sig. B',
				src:[''], //???
				metadata: '',
				creator: 'Congregatio de Propaganda Fide',
				textTitle: 'Alphabeta varia',
				place: 'Rome, Italy',
				year: '1630',
				narrative: '[NEEDS IMAGES] Many of the languages that appear in polyglots had rarely, if ever, been printed before. This forced early polyglot scholars to find printers skilled enough to make new print types from scratch, often using manuscript sources. Arnao Gúillen de Brocar, the printer of the Complutensian polyglot, developed six new type founts for the work using the manuscripts Cisneros had collected. A century later, the Catholic church sought to make it easier to print in these languages by circulating print specimens taken from particular sources, such as the one pictured here, which printers throughout Europe could use to make their own types.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=286133',
					otherAuthor: ['Hall, Basil.'],
					otherTitle: ['The Great Polyglot Bibles.'],
					otherBib: ['Publication number 124 of the Book Club of California. San Francisco: Published for its members by the Book Club of California, 1966.'],
				},
			],
			translations: [
					{
						id: 'ct1',
						type: 'Latin Translation of Septuagint Text',
						category: 'translations',
						title: 'Learning Greek',
						subtitle: 'Polyglots bring Greek into conversation with Hebrew for first time',
						image: 'VAULT Wing ZP 538 .F92848, pp. 26-27',
						src:['./resampled/wing_zp_538_f9284_tp.jpg', './resampled/wing_zp_538_f9284_sig_a1r.jpg','./resampled/wing_zp_538_f9284_pg_901.jpg', './resampled/wing_zp_538_f9284_pg_901_detail.jpg'], //which in which location
						metadata: '',
						creator: '',
						textTitle: 'Sefer Tehilim = Psalterium Hebraicum.',
						place: 'Basel, Switzerland',
						year: '1563',
						narrative: 'Polyglot scholars hoped that their readers would study the Bible in all the languages presented in these books, but they recognized the fact that few Europeans (even educated ones) were able to do so. Care was always taken to provide Latin translations of these other languages, so that users could see how the different languages related to each other. Demetrius Ducas, the Greek scholar tasked with preparing the Septuagint edition in the Complutensian, included a Latin translation that differed considerably from the Vulgate translation next to it. He hoped to inspire the same sort of work we see in the Hebrew Psalter pictured here, in which scholars were comfortable using Latin, Hebrew, and Greek to understand the text of the Bible. ',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=952285',
						otherAuthor: ['Fernández Marcos, Natalio. “Greek Sources of the Complutensian Polyglot.” '],
						otherTitle: ['Jewish Reception of Greek Bible Versions: Studies in Their Use in Late Antiquity and the Middle Ages.'],
						otherBib: ['Tübingen: Siebeck, 2009, 302-315.'],

					},
					{
						id: 'ct2',
						type: 'Vulgate',
						category: 'translations',
						title: 'Calvary on the page',
						subtitle: 'Printers use page layout to protect the authority of the Vulgate',
						image: 'Wing oversize ZP 5465 .P7013 from Plantin Polyglot',
						src:['./plantin-tests.jpg'], //no matching imagery
						metadata: '',
						creator: 'Christopher Plantin, printer',
						textTitle: 'Plantin Polyglot',
						place: 'Antwerp, Belgium',
						year: '1571',
						narrative: '[NEEDS IMAGES] Not everyone was excited about polyglots. Many scholars and ecclesiastical leaders argued that a polyglot edition would ruin Scripture, since it would allow the language of murderers (Jews) and heretics (Greeks) to distract readers from the essential Latin text. The Complutensian scholars refused to leave out these original languages, but placed the Vulgate in the very center of the page, with the Hebrew and Greek alongside. They described it as a representation of the Crucifixion, with Christ flanked by thieves on either side. As the image shows, the Plantin polyglot takes the same visual approach in order to appease the Catholic church. Due to its Protestant origin, the London Polyglot did not bother with this, giving more prominence to the other original languages.',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=234961',
						otherAuthor: ['Fernández Marcos, Natalio. “The First Polyglot Bible.” '],
						otherTitle: ['In The Text of the Hebrew Bible and Its Editions: Studies in Celebration of the Fifth Centennial of the Complutensian Polyglot. Supplements to the Textual History of the Bible 1.'],
						otherBib: ['Leiden: Brill, 2014, 3-18.'],
					},
				],
			tools: [
				{
					id: 'cto1',
					type: 'Hebrew/Aramaic Root words',
					category: 'tools',
					title: 'Finding Fullness of the Word',
					subtitle: 'Polyglot scholars promoted understanding Hebrew',
					image: 'VAULT Case folio C 211 .51, v. 6, f. clxii – Hebrew Vocabulary in Complutensian',
					src: ['./resampled/case_c_211_51_sig_b3v_b4r.jpg', './resampled/case_c_211_51_tp.jpg'],
					//larger version of b3v_b4r for computensia overlays
					metadata: '(Creator, Title, Place of Creation, Creation Year)',
					creator: '',
					textTitle: 'Hebrew Vocabulary',
					place: 'Alcalá de Henares, Spain',
					year: '1517',
					narrative: 'Hebrew, believed by many to be God’s language, was a critical component of any polyglot Bible, and features prominently in all of them. Hebrew in particular was to be the centerpiece of the Complutensian polyglot, since Cisneros believed that it contained the fullest meaning and mystery of God’s Word. Understanding Hebrew depended on understanding its root words, the building blocks on which all Hebrew vocabulary (and thus all of Scripture) were built. The Complutensian scholars hoped to promote the learning of Hebrew by including root words that were keyed to entries in the Hebrew vocabulary located in the sixth volume. By learning these words, users could better grasp the full range of meaning behind the Hebrew language, which would open the door to the deep spiritual mysteries it expressed.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=398508',
					otherAuthor: ['Otero, Andrés Piquer and Pablo Torijano Morales, eds. '],
					otherTitle: ['The Text of the Hebrew Bible and Its Editions: Studies in Celebration of the Fifth Centennial of the Complutensian Polyglot.'],
					otherBib: ['Supplements to the Textual History of the Bible 1. Leiden: Brill, 2014.'],
				},
				{
					id: 'cto2',
					type: 'MS Annotations on Hebrew',
					category: 'tools',
					title: 'Learning God’s Language',
					subtitle: 'Polyglots make widespread study of Hebrew more available',
					image: 'VAULT Wing folio ZP 538 .F9284, p. SOMETHING',
					src:['./resampled/wing_zp_538_f9284_tp.jpg', './resampled/wing_zp_538_f9284_sig_a1r.jpg','./resampled/wing_zp_538_f9284_pg_901.jpg', './resampled/wing_zp_538_f9284_pg_901_detail.jpg'], //which for which location ?
					metadata: '',
					creator: 'Johann Forster',
					textTitle: 'Dictionarium Hebraicum nouum',
					place: 'Basel, Switzerland',
					year: '1557',
					narrative: 'By making available definitive texts of the Bible in its original languages, polyglot scholars hoped to inspire other intellectuals to learn to use these languages on their own, so that the quality of Christian scholarship would grow. We can see this in action in the Newberry’s copy of the Complutensian; an early user wrote Latin translations over the Hebrew words in this copy that are different from the Vulgate, which suggests that he used the book to learn Hebrew. In the process, he may have made use of a Latin-Hebrew dictionary like the one compiled by the scholar Johann Forster, who proudly claimed that his dictionary was based solely on biblical sources, which the Complutensian provided in abundance.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=182836',
					otherAuthor: ['Bell, Dean Phillip.'],
					otherTitle: ['Jews in the Early Modern World.'],
					otherBib: ['New York: Rowman & Littlefield, 2008, 227-230.'],
				},
				{
					id: 'cto3',
					type: 'Hebrew/Targum Root Words',
					category: 'tools',
					title: 'Interpretive Editions',
					subtitle: 'Polyglot editors interpret Hebrew before printing it',
					image: 'Wing ZP 539 G 94 sig b2r b1v',
					src: [ './resampled/wing_zp_539_g94_tp.jpg', './resampled/wing_zp_539_g94_sig_b2r_b1v.jpg', './resampled/wing_zp_539_g94_sig_b3r_b2v.jpg', './resampled/wing_zp_539_g94_sig_b3v_b4r.jpg' ],
					metadata: '',
					creator: 'Rabbi David Kimhi',
					textTitle: 'Liber Michlol',
					place: 'Paris',
					year: '1540',
					narrative: 'Classical Hebrew is composed of only consonants in its written form; readers could decide which vowels to supply when reading it, which could dramatically alter the meaning of the word. This forced editors to make decisions about how certain words could be interpreted, especially when they were compared with the Latin or Greek versions. Scholars did this by relying on Hebrew grammars, which offered guidance on how particular words ought to be pronounced. The Complutensian scholars relied especially on the work of Rabbi David Kimhi, an influential medieval grammarian whose work remained popular in the early modern period, as evidenced by the printed example shown here. ',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=483893',
					otherAuthor: ['Reuchlin, Johann.'],
					otherTitle: ['De accentibus et orthographia linguae Hebraicae.'],
					otherBib: ['Haguenau, 1518. VAULT Case PJ4581 .R4 1518'],
				},
				],
			other: '',
		},

antwerp: {
	fullName: 'Plantin Polyglot (New Testament) – Open to Acts 2',
		sources: [
					{
						id: 'as1',
						type: 'Syriac Text',
						category: 'sources',
						title: 'The Syriac Bible',
						subtitle: 'Polyglot scholars seek out manuscripts of a new biblical language',
						image: 'VAULT Hebrew MS 25, f. 93, 139, 178, 321',
						src:['./resampled/hebrew_ms_25_fc.jpg', './resampled/hebrew_ms_25_pg_80.jpg', './resampled/hebrew_ms_25_pg_90_91.jpg', './resampled/hebrew_ms_25_pg_92_93.jpg', './resampled/hebrew_ms_25_pg_94_95.jpg', './resampled/hebrew_ms_25_pg_138_139.jpg', './resampled/hebrew_ms_25_pg_176_177.jpg', './resampled/hebrew_ms_25_pg_178_179.jpg', './resampled/hebrew_ms_25_pg_320_321.jpg', './resampled/hebrew_ms_25_pg_322_323.jpg'],
						metadata: '',
						creator: 'Syriac Gospel Lectionary',
						place: '',
						year: '13th-15th century',
						narrative: 'During the age of the great polyglots, scholars were keen to bring in any new ancient biblical languages that came to their attention. The first of these was Syriac, which was introduced to Europeans at the Fifth Lateran Council (1512-1517). Syriac was a literary language that was very close to Aramaic (though it had a different alphabet), and scholars were convinced that this was the language spoken by Christ, Mary, and the apostles. More importantly for polyglot creators, the first translation of the New Testament was into Syriac, in a version known as the Peshitta. Scholars and printers throughout Europe were eager to bring this early translation into print, and acquired manuscripts to make the necessary typefaces. Plantin’s polyglot used a 13th-century copy of the Peshitta; the Newberry’s copy shown here dates from the same time.',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=844229',
						otherAuthor: ['Contini, Riccardo. “Gli inizi della linguistica siriaca nell’Europa rinascimentale,” in ', 'Wilkinson, Robert J.'],
						otherTitle: ['Italia ed Europa nella linguistica del Rinascimento.', 'The Kabbalistic Scholars of the Antwerp Polyglot Bible.'],
						otherBib: ['(Bib ID: 135672), pp. 483-502','Leiden: Brill, 2007.'],
					},
					{
						id: 'as2',
						type: 'Greek Text',
						category: 'sources',
						title: 'Greek Manuscripts',
						subtitle: 'Polyglot editors reveal the Greek New Testament',
						image: 'VAULT Greek MS 2, ff. 1v-2',
						src:['./resampled/greek_ms_002_foilo_1r.jpg', './resampled/greek_ms_002_foilo_1v.jpg'],
						metadata: '',
						creator: 'Gospels',
						textTitle: '',
						place: '',
						year: '12th century',
						narrative: '[NEEDS FINAL TEXT] Knowing Greek i.	Definitely use the reference to humanism, but point out how it was crucial for these guys to get manuscripts in Greek in order to do their work. More people knew about it, but you still had to go with the manuscripts ii.	Talk about collecting Greek Manuscripts; Complutense scholars got theirs from the Vatican…we think. Find out where others got theirs…',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=160179',
						otherAuthor: [''],
						otherTitle: [''],
						otherBib: [''],
					},
					{
						id: 'as3',
						type: 'Greek Text (could be anything here)',
						category: 'sources',
						title: 'Acquiring Manuscripts',
						subtitle: 'Polyglot editors depend on merchants and diplomats to acquire the sources, they need.',
						image: 'Case G 601 .137, Title Page',
						src:['./resampled/case_g_601_137_tp_frontis.jpg', './resampled/case_g_601_137_frontis.jpg'],
						metadata: '',
						creator: 'Ogier Ghislan de Busbecq',
						textTitle: 'The four epistles of A.G. Busbequius, concerning his embassy into Turkey.',
						place: 'London',
						time: '1694',
						narrative: '[NEEDS FINAL TEXT] i.	Now get to the money. People couldn’t do this without significant help, especially diplomats, scholars, and other people going into the Ottoman Empire and acquiring these manuscripts. Mention that this gets easier as the polyglot age goes on, as relations increase. ii.	Talk about Busbecq, who he is, and how he loved to go purchase manuscripts, especially Greek ones.',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=269378',
						otherAuthor: [''],
						otherTitle: [''],
						otherBib: [''],
					},
				],
				translations: [
				{
					id: 'at1',
					type: 'Greek and Latin Text',
					category: 'translations',
					title: 'The Polyglot Effect',
					subtitle: 'Printers place the entire Word of God before readers',
					image: 'Bonaparte 1928, Sig. A3 verso – A4',
					src:['./resampled/bon_1928_sig_a3v_a4r.jpg', './resampled/bon_1928_tp.jpg'],
					metadata: '',
					creator: 'Hieronymus Megiser',
					textTitle: 'Specimen quinquaginta diversarum atque inter se differentium linguarum, & dialectorum',
					place: 'Frankfurt am Main, Germany',
					year: '1603',
					narrative: '[NEEDS FINAL TEXT] Talk about the reason why polyglotters wanted these languages together; it was to undo the Tower of Babel. So showing them next to each other was probably a good thing. Things just got crazier as the polyglots went on, all the way up to 9 by the time we get to London. Talk about the history of this text, mention the languages that do not appear in the example, but the idea is that it’s the same text being shown all the time.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=666622',
					otherAuthor: [''],
					otherTitle: [''],
					otherBib: [''],
				},
				{
					id: 'at2',
					type: 'Latin Vulgate',
					category: 'translations',
					title: 'Royal Patronage',
					subtitle: 'Polyglots as signs of political power',
					image: 'Wing oversize ZP 5465 .P7013, frontispiece',
					src:'', //no 5465
					metadata: '',
					creator: 'Pieter van der Heyden',
					textTitle: '',
					place: 'Antwerp, Belgium',
					year: '1571',
					narrative: 'Due to their extremely high cost, all of the great polyglots required the assistance of the state. This forced their creators to play delicate games of diplomacy between secular and ecclesiastical authorities in order to finish them. Plantin had a more difficult time than most; many of the contributors to the project (including Plantin himself) were suspected Protestants. A crisis ensued when, with the polyglot project well under way, a Protestant revolt in the Netherlands led to a brutal repression by the Spanish in 1567. Plantin faced financial ruin in the aftermath, but he used the polyglot to save himself (and his business), pitching it as both a monument of Catholic piety and a scholarly tool to combat Protestantism. His rebranding efforts won the support of Philip II, who ensured that the project would be completed. The spectacular frontispiece in the first volume of the finished edition commemorated Philip’s support.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=234961',
					otherAuthor: [''],
					otherTitle: ['Correspondance de Christophe Plantin,'],
					otherBib: ['Epp. 39-47. '],
					},
					{
						id: 'at3',
						type: 'Hebrew Text',
						category: 'translations',
						title: 'Transliterating New Languages',
						subtitle: 'Scholars use Hebrew to unlock other Near Eastern languages',
						image: 'Wing ZP 556 .Z61 – Sig. A4v-B4; Sig. B2v-B3; Sig. F4v-G',
						src:['./resampled/wing_zp_556_z61_tp.jpg', './resampled/wing_zp_556_z61_010.jpg','./resampled/wing_zp_556_z61_011.jpg', './resampled/wing_zp_556_z61_sig_a2r.jpg', './resampled/wing_zp_556_z61_sig_a3r_a2v.jpg', './resampled/wing_zp_556_z61_sig_a4v_b1r.jpg', './resampled/wing_zp_556_z61_sig_b1r.jpg', './resampled/wing_zp_556_z61_sig_b3r_b2v.jpg', './resampled/wing_zp_556_z61_sig_f5v_g1r.jpg'],
						metadata: '',
						creator: 'Johann Widmanstetter, ed.',
						textTitle: 'Syriacae lingvae Iesv Christo, eivsque Matri Virgini atq; Iudaeis omnibus, Christianae redemptionis Euangelicaeq́…',
						place: 'Vienna',
						year: '1555',
						narrative: 'Christians in Europe assumed that Near Eastern Christians were backward, misguided, and ignorant of Christian doctrine. In part, the polyglots were made to help Europeans learn the languages needed to minister to their wayward brethren. Syriac was one of these, but, like many Near Eastern languages, hardly anyone in Europe was familiar with it. To get around that problem, polyglot scholars used more familiar languages to help readers access unfamiliar ones. For the Antwerp polyglot, Plantin’s collaborators decided to transliterate the Peshitta into Hebrew, so scholars could begin to grasp how the Syriac alphabet worked. They could then use the accompanying Latin paraphrases to translate it. In so doing, Plantin’s team followed the same approach taken by Johann Widmanstetter, the first European to print the Peshitta in 1555. That edition was accompanied by this short text, which used Hebrew and Latin to help scholars master the Syriac alphabet.',
						link: '',
						otherAuthor: ['i.	Wilkinson, Robert J. '],
						otherTitle: ['Orientalism, Aramaic, and Kabbalah in the Catholic Reformation: The First Printing of the Syriac New Testament.'],
						otherBib: ['Leiden: Brill, 2007.'],
					},
				],
				tools: [
				{
					id: 'ato1',
					type: 'Syriac Translation',
					category: 'tools',
					title: 'Philology and Near Eastern Studies',
					subtitle: 'Polyglots open up new forms of inquiry using Near Eastern languages',
					image: 'Case folio F 017 .788, Title Page',
					src:['./resampled/case_f_017_788_tp.jpg', './resampled/case_f_017_788_pg_286_287.jpg', './resampled/case_f_017_788_pg_326_327.jpg'],
					metadata: '',
					creator: 'Joseph Scaliger',
					textTitle: 'De emendatione temporum',
					place: 'Paris, France',
					year: '1583',
					narrative: '[NEEDS FINAL TEXT] I. Another example of what this information produced by the polyglots helped make possible: the historical and philological study of Near Eastern cultures. Other scholars and humanists took the knowledge of languages etc. and used them to do other kinds of work. ii.	Talk about Scaliger and what he tries to do with this work, figure out how far back history goes and how to measure time, make clear the connection between his work and the Syriac in the polyglot.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=656475',
					otherAuthor: [''],
					otherTitle: [''],
					otherBib: [''],
				},
				],
			other: '',
		},

london: {
		fullName: 'London Polyglot – Open to Proverbs 1',
		sources: [
			{
				id: 'ls1',
				type: 'Hebrew Text',
				category: 'sources',
				title: '',
				subtitle: '',
				image: 'no image',
				src: '',
				metadata:'',
				creator: '',
				textTitle: '',
				place: '',
				time: '',
				narrative: '[NEEDS FINAL TEXT + IMAGES] Founding letter types: Though the Hebrew is the “least good” of the types, we should mention here that these things often had to be made from scratch. London in particular was probably the work of multiple artists (see Reed, p. 163), so you can talk about that.',
				link:'',
				otherAuthor: [''],
				otherTitle: [''],
				otherBib: [''],
			},
			{
				id: 'ls2',
				type: 'Vulgate Text',
				category: 'sources',
				title: 'Polyglots as Bibles',
				subtitle: 'Other works help readers approach polyglots like any other Bible',
				image: 'Case folio BS485 .C93 1660, v. 4, p. 5286',
				src:['./resampled/case_bs_485_c93_1660_pg_5283_5286.jpg', './resampled/case_bs_485_c93_1660_tp_02.jpg', '/public/resampled/case_bs_485_c93_1660_tp_01.jpg'],
				metadata: '',
				creator: '•	John Pearson, editor.',
				textTitle: 'Critici sacri, sive, Doctissimorum virorum in SS. Biblia annotationes, & tractatus.',
				place: 'London, England',
				year: '1660',
				narrative: 'With all of their scholastic apparatus, it can be easy to forget that polyglots were still Bibles. As such, the creators of the great polyglots expected people to use them to learn about God. Indeed, polyglots were considered the most definitive editions of biblical texts available that would reveal the spiritual meaning of the Word in its deepest sense. Since using them was no easy task, however, scholars also developed materials to help readers get as much spiritual value out of the polyglots as possible. The text shown here, a collection of commentaries on all the books of the Bible, is an example of one of these aids. This project was spearheaded by John Pearson, one of the early advocates for the London polyglot, and was perhaps intended to supplement Walton’s great work.', //comment on extending this info in word document.
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=236649',
				otherAuthor: ['Reed,'],
				otherTitle: ['History of the English Letter-Founders.'],
				otherBib: [''],
				},
		],
		translations: [
			{
				id: 'lt1',
				type: 'Septuagint Text',
				category: 'translations',
				title: 'Matching Prints',
				subtitle: 'Printers rise to the challenge of presenting the same text.',
				image: 'Case oversize C 211 .657, v. 3, pp. 118-119',
				src:['./resampled/case_c_211_657_pg_118_119.jpg', './resampled/case_c_211_657_pg_322_323.jpg'],
				//larger version of 118-119 for london overlays
				metadata: '',
				creator: '',
				textTitle: 'Biblia sacra polyglotta',
				place: 'London, England',
				year: '1657',
				narrative: '[NEEDS FINAL TEXT] This is where we should make the point about how the printers themselves were involved in this activity; the fact that every passage here shows the exact same amount of text is quite remarkable, and fits into the idea of showing them the Word.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=236649',
				otherAuthor: [''],
				otherTitle: [''],
				otherBib: [''],
			},
		],
		tools: [
			{
				id: 'lto1',
				type: 'Targum Text',
				category: 'tools',
				title: 'Supporting Oriental Studies',
				subtitle: 'Polyglots lead to creation of other linguistic material',
				image: 'Case oversize X 442 .15, sig. A',
				src:['./resampled/case_x_422_15_sig_a2r.jpg', './resampled/case_x_422_15_sig_a2v_b3r.jpg', './resampled/case_x_422_15_tp.jpg'],
				metadata: '',
				creator: 'Edmund Castell',
				textTitle: 'Lexicon heptaglotton',
				place: 'London, England',
				year: '1669',
				narrative: '[NEEDS FINAL TEXT] Talk more about Oriental Studies, with specific reference to learning how to read, speak, and write in these other Near Eastern languages. Explain this text, a giant dictionary for all seven of the languages used in the London polyglot, which was made in connection with this work.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=287925',
				otherAuthor: [''],
				otherTitle: [''],
				otherBib: [''],
			},
			{
				id: 'lto2',
				type: 'Targum Translation',
				category: 'tools',
				title: 'Preparing the way for the Polyglot',
				subtitle: 'Scholars create texts to help others use polyglots',
				image: 'Case X 3 .44, pp. 38-39 ',
				src:['./resampled/case_x_3_44_pg_38_39.jpg', './resampled/case_x_3_44_tp.jpg'],
				metadata: '',
				creator: 'Brian Walton',
				textTitle: 'Introductio ad Lectionem Linguarum Orientalium',
				place: 'London, England',
				year: '1655',
				narrative: 'Oriental Studies: Polyglots were made to be used, but their creators did not assume that anyone would be able to do this without help. They worked hard to prepare the public to be able to get the most use out of them. For instance, one of Walton’s primary goals for his polyglot was to prepare missionaries to correct troubling religious practices and beliefs among Near Eastern Christians. This short work, published two years before the polyglot was finished, was intended to help achieve this goal. It taught readers how to read, write, and pronounce the Near Eastern languages that would appear in the polyglot. With this background, the London polyglot became a kind of textbook that missionaries and scholars could use to communicate with Eastern Christians in their native tongues.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=764078',
				otherAuthor: ['Roger Williams, '],
				otherTitle: ['Key to the Language of America. '],
				otherBib: [''],
			},
			{
				id: 'lto3',
				type: 'Arabic Text',
				category: 'tools',
				title: 'Arabic Studies',
				subtitle: 'Polyglots stimulate interest in Arabic materials',
				image: 'Wing ZP 535 .M4677, pp. 60-61',
				src:['./resampled/wing_zp_535_m4677_pg_60_61.jpg', './resampled/wing_zp_535_m4677_tp.jpg' ],
				metadata: '',
				creator: '',
				textTitle: 'Alphabetum arabicum',
				place: 'Rome, Italy',
				year: '1592',
				narrative: '[NEEDS FINAL TEXT] Talk about the growing importance of Arabic studies, mention how London polyglot began with founding of Arabic chair at Oxford. Explain what kind of text this is, point out the Medici press’s focus on conversion and Arabic materials, which the British would have used.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=193340',
				otherAuthor: [''],
				otherTitle: [''],
				otherBib: [''],
			},
			{
				id: 'lto4',
				type: 'Syriac Translation',
				category: 'tools',
				title: 'Preaching from the Polyglot',
				subtitle: 'Polyglots support preachers by providing context for the Bible',
				image: 'C 9911 .0755, sig. B verso',
				src:['./resampled/c_9911_0755_%20005.jpg','./resampled/c_9911_0755_%20006.jpg','./resampled/c_9911_0755_%20007.jpg','./resampled/c_9911_0755_%20008.jpg','./resampled/c_9911_0755_%20009.jpg','./resampled/c_9911_0755_%20010.jpg','./resampled/c_9911_0755_%20011.jpg','./resampled/c_9911_0755_%20012.jpg','./resampled/c_9911_0755_%20013.jpg','./resampled/c_9911_0755_%20014.jpg','./resampled/c_9911_0755_%20015.jpg','./resampled/c_9911_0755_%20016.jpg','./resampled/c_9911_0755_%20017.jpg','./resampled/c_9911_0755_%20018.jpg','./resampled/c_9911_0755_%20019.jpg'],
				metadata: '',
				creator: 'Shute Barrington',
				textTitle: 'A sermon preached before the Lords Spiritual and Temporal in the Abbey Church of Westminster on Thursday, January 30, 1772',
				place: 'London, England',
				year: '1772',
				narrative: '[NEEDS FINAL TEXT] Talk about how these books were used for preaching; preachers in this period wanted to have the best version of the text to be able to preach the Word effectively to their congregations. Explain how this sermon was produced by using the Newberry’s copy of the London Polyglot, and how this image points to this very verse. Also point out that Barrington owned our copy of the Lexicon heptaglotton.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=217355',
				otherAuthor: [''],
				otherTitle: [''],
				otherBib: [''],
			},
			{
				id: 'lto5',
				type: 'Arabic Translation',
				category: 'tools',
				title: 'Conversion and Education',
				subtitle: 'Polyglots pave the way for converting and education Near Eastern Christians',
				image: 'Wing folio ZP 845 .H6905, Proverbs 1',
				src:[''], //no materials for 845 yet.
				metadata: '',
				creator: '',
				textTitle: 'The Holy Bible, containing the Old and New Testaments, in the Arabic language.',
				place: 'Newcastle-upon-Tyne, England',
				year: '1811',
				narrative: '[NEEDS FINAL TEXT + IMAGES] Bibles Beget Bibles: Talk about conversion here, remind people of how the polyglots were supposed to help get to the Christians in the East. Talk about this particular Bible, note that the Arabic text was based on the London polyglot, and was also produced under the auspices of Shute Barrington.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=236660',
				otherAuthor: [''],
				otherTitle: [''],
				otherBib: [''],
			}
		],
			other: '',
	},
};


///public/resampled/case_c3_52_folio_1r.jpg - hebrew folio page...
//public/resampled/inc_7763_tp.jpg - prima pars biblia cue?
///public/resampled/x_4905_1_tp.jpg - arabic

