export const eachPanel = {
	comp: {
		fullName: 'Complutensian Polyglot (Old Testament) – Open to Genesis 8',
		sources: [
			{
				id: 'cs1',
				type: 'Hebrew Text',
				category: 'sources',
				title: 'Making the Hebrew Text',
				subtitle: 'Scholars use medieval manuscripts to create the Hebrew text',
				image: 'VAULT folio Bonaparte 5022 no. 9 binding 1',
				src:'',
				metadata: '',
				creator: '',
				textTitle: 'First Chronicles in Hebrew',
				place: 'Spain',
				year: '11th century',
				narrative: 'All polyglot texts were ultimately based on manuscript copies of biblical texts. Thanks to its thriving Jewish community, Spain was the leading center of Hebrew scholarship since the Middle Ages. Everyone agreed that the highest quality Hebrew manuscripts were produced there, so Cisneros was well-positiond to acquire the best proof texts on which to base the Complutensian’s Hebrew edition, and the conversos recruited to produce it – Pablo Coronel, Alfonso de Toledo, and Alfonso de Zamora – all had extensive experience working with these manuscript sources. Even the later polyglots turned to Spanish manuscripts to produce their versions. The manuscript displayed above is the Newberry’s oldest Hebrew manuscript, a fragment of the Book of Chronicles that was made in Spain at some point in the 11th century.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=961738',
				otherAuthor: 'Ortega-Monasterio, Teresa. “Spanish Biblical Hebrew Manuscripts.” ',
				otherTitle: 'Hebrew Studies',
				otherBib: '45 (2004), 163-74.',
			},
			{
				id: 'cs2',
				type:'Vulgate',
				category: 'sources',
				title: 'The Vulgate',
				subtitle: 'The standard Latin translation of the Bible poses a challenge to polyglot scholars',
				image: 'Case MS 216 folio 005v',
				src:'',
				metadata: '',
				creator: '',
				textTitle: '[Bible][Manuscript]',
				place: 'France(?)',
				year: 'Ca. 1230-1250',
				narrative: 'Throughout the Middle Ages, the dominant version of the Bible was the Latin translation made in the 4th century that was attributed to St. Jerome. By the 16th century, scholars agreed that it was a very problematic text, filled with questionable translations and 1,000 years of inherited scribal errors that scholars were eager to fix. The Roman Church, however, considereed the Vulgate the definitive translation, and forbade anyone from making a corrected edition. As a result, the Complutensian scholars built their edition of the Vulgate from medieval manuscripts in Spain, none of which were complete. The Vulgate shown here a complete version of a 13th-century manuscript of the Vulgate from France.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=814053',
				otherAuthor: '[Evangelistary] [manuscript]. Germany, between 1050 and 1100. VAULT folio Case MS 4',
				otherTitle: '',
				otherBib: '',
			},
			{
				id: 'cs3',
				type: 'Targum Text',
				category: 'sources',
				title: 'Aramaic',
				subtitle: 'Scholars use medieval manuscripts to locate the first translation of the Old Testament',
				image: 'VAULT Hebrew MS 1, folio 6r-5r',
				src:'',
				metadata: '',
				creator: ' ',
				textTitle: 'Targum Onkelos of the Pentateuch',
				place: 'Italy',
				year: '14th century',
				narrative: 'To represent as much of the divine mystery as possible, the Complutensian scholars decided to include the Targum, a paraphrase of the Hebrew Scriptures in Aramaic, the language that Jews spoke after classical Hebrew died out as a spoken vernacular. Manuscripts of it – such as this example from the Newberry’s collections – were widely used in Jewish synagogues throughout Europe to explain and interpret the Hebrew text. The Targum was both a translation and an explanation, incorporating commentary from generations of rabbis and even some Talmudic fables along with the text. This made it somewhat difficult to use as a source for a definitive text of the Bible, and the Complutensian only included the Targum for the first volume of the Bible (which contained the Pentateuch). Later polyglots would include the entire Targum, after more editorial work had been done.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=124482',
				otherAuthor: 'Münster, Sebastian.',
				otherTitle: 'ʻArukh : dictionarium chaldaicum non ta[m] ad chaldaicos interpretes q[uam] rabbinoru[m] intelligenda co[m]mentaria necessarium.',
				otherBib: 'Basel, 1527. VAULT Case PJ4937 .M86 1527',
			},
			{
				id: 'cs4',
				type:'Septuagint Text (Greek)',
				category: 'sources',
				title: 'The Septuagint',
				subtitle: 'The Greek translation of the Old Testament gains new life in the polyglots',
				image: 'Folio Inc. 5966, f. something',
				src: '',
				metadata: '',
				creator: '',
				textTitle: '[Psalterium Graeco-Latinum cum canticis].',
				place: 'Milan, Italy',
				year: '1481',
				narrative: 'Centuries before the birth of Christ, Greek-speaking Jews living in Egypt created a Greek translation of the Old Testament called the Septuagint, so-called because around 70 (Septuagint is the Latin word for 70) scholars produced it. During the Middle Ages, the Septuagint was relatively unknown in western Europe, where Jerome’s Vulgate translation dominated. Interest in learning and using Greek in religious studies grew throughout the 14th and 15th centuries, especially after the fall of Constantinople to the Ottoman Turks in 1453. Thereafter, Biblical material in Greek began to appear in print, beginning with the psalter pictured here. Inspired by this, Cisneros borrowed Septuagint manuscrips from the Vatican to produce the first printed edition of the entire Septuagint Old Testament in his polyglot.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=400646',
				otherAuthor: 'O’Connell, S.',
				otherTitle: 'From Most Ancient Sources: The Nature and Text-Critical Use of the Greek Old Testament Text of the Complutensian Polyglot Bible.',
				otherBib: 'Fribourg/Göttingen: Vandenhoeck and Ruprecht, 2006.',

			},
			{
				id: 'cs5',
				type: 'Hebrew Text',
				category: 'sources',
				title: 'Making Hebrew Type',
				subtitle: 'Letter-founders create new typefaces for polyglots',
				image: 'Case Wing Z 40535 .156, sig. B',
				src:'',
				metadata: '',
				creator: 'Congregatio de Propaganda Fide',
				textTitle: 'Alphabeta varia',
				place: 'Rome, Italy',
				year: '1630',
				narrative: 'Many of the languages that appear in polyglots had rarely, if ever, been printed before. This forced early polyglot scholars to find printers skilled enough to make new print types from scratch, often using manuscript sources. Arnao Gúillen de Brocar, the printer of the Complutensian polyglot, developed six new type founts for the work using the manuscripts Cisneros had collected. A century later, the Catholic church sought to make it easier to print in these languages by circulating print specimens taken from particular sources, such as the one pictured here, which printers throughout Europe could use to make their own types.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=286133',
					otherAuthor: 'Hall, Basil.',
					otherTitle: 'The Great Polyglot Bibles.',
					otherBib: 'Publication number 124 of the Book Club of California. San Francisco: Published for its members by the Book Club of California, 1966.',
				},
			],
			translations: [
					{
						id: 'ct1',
						type: 'Latin Translation of Septuagint Text',
						category: 'translations',
						title: 'Learning Greek',
						subtitle: 'Polyglots bring Greek into conversation with Hebrew for first time',
						image: 'VAULT Wing ZP 538 .F92848, pp. 26-27',
						src:'',
						metadata: '',
						creator: '',
						textTitle: 'Sefer Tehilim = Psalterium Hebraicum.',
						place: 'Basel, Switzerland',
						year: '1563',
						narrative: 'Polyglot scholars hoped that their readers would study the Bible in all the languages presented in these books, but they recognized the fact that few Europeans (even educated ones) were able to do so. Care was always taken to provide Latin translations of these other languages, so that users could see how the different languages related to each other. Demetrius Ducas, the Greek scholar tasked with preparing the Septuagint edition in the Complutensian, included a Latin translation that differed considerably from the Vulgate translation next to it. He hoped to inspire the same sort of work we see in the Hebrew Psalter pictured here, in which scholars were comfortable using Latin, Hebrew, and Greek to understand the text of the Bible. ',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=952285',
						otherAuthor: 'Fernández Marcos, Natalio. “Greek Sources of the Complutensian Polyglot.” ',
						otherTitle: 'Jewish Reception of Greek Bible Versions: Studies in Their Use in Late Antiquity and the Middle Ages.',
						otherBib: 'Tübingen: Siebeck, 2009, 302-315.',

					},
					{
						id: 'ct2',
						type: 'Vulgate',
						category: 'translations',
						title: 'Calvary on the page',
						subtitle: 'Printers use page layout to protect the authority of the Vulgate',
						image: 'Wing oversize ZP 5465 .P7013 from Plantin Polyglot',
						src:'',
						metadata: '',
						creator: 'Christopher Plantin, printer',
						textTitle: 'Plantin Polyglot',
						place: 'Antwerp, Belgium',
						year: '1571',
						narrative: 'Not everyone was excited about polyglots. Many scholars and ecclesiastical leaders argued that a polyglot edition would ruin Scripture, since it would allow the language of murderers (Jews) and heretics (Greeks) to distract readers from the essential Latin text. The Complutensian scholars refused to leave out these original languages, but placed the Vulgate in the very center of the page, with the Hebrew and Greek alongside. They described it as a representation of the Crucifixion, with Christ flanked by thieves on either side. As the image shows, the Plantin polyglot takes the same visual approach in order to appease the Catholic church. Due to its Protestant origin, the London Polyglot did not bother with this, giving more prominence to the other original languages.',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=234961',
						otherAuthor: 'Fernández Marcos, Natalio. “The First Polyglot Bible.” ',
						otherTitle: 'In The Text of the Hebrew Bible and Its Editions: Studies in Celebration of the Fifth Centennial of the Complutensian Polyglot. Supplements to the Textual History of the Bible 1.',
						otherBib: 'Leiden: Brill, 2014, 3-18.',
					},
				],
			tools: [
				{
					id: 'cto1',
					type: 'Hebrew/Aramaic Root words',
					category: 'tools',
					title: 'Finding Fullness of the Word',
					subtitle: 'Polyglot scholars promoted understanding Hebrew',
					image: 'VAULT Case folio C 211 .51, v. 6, f. clxii – Hebrew Vocabulary in Complutensian',
					src: '',
					metadata: '(Creator, Title, Place of Creation, Creation Year)',
					creator: '',
					textTitle: 'Hebrew Vocabulary',
					place: 'Alcalá de Henares, Spain',
					year: '1517',
					narrative: 'Hebrew, believed by many to be God’s language, was a critical component of any polyglot Bible, and features prominently in all of them. Hebrew in particular was to be the centerpiece of the Complutensian polyglot, since Cisneros believed that it contained the fullest meaning and mystery of God’s Word. Understanding Hebrew depended on understanding its root words, the building blocks on which all Hebrew vocabulary (and thus all of Scripture) were built. The Complutensian scholars hoped to promote the learning of Hebrew by including root words that were keyed to entries in the Hebrew vocabulary located in the sixth volume. By learning these words, users could better grasp the full range of meaning behind the Hebrew language, which would open the door to the deep spiritual mysteries it expressed.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=398508',
					otherAuthor: 'Otero, Andrés Piquer and Pablo Torijano Morales, eds. ',
					otherTitle: 'The Text of the Hebrew Bible and Its Editions: Studies in Celebration of the Fifth Centennial of the Complutensian Polyglot.',
					otherBib: 'Supplements to the Textual History of the Bible 1. Leiden: Brill, 2014.',
				},
				{
					id: 'cto2',
					type: 'MS Annotations on Hebrew',
					category: 'tools',
					title: 'Learning God’s Language',
					subtitle: 'Polyglots make widespread study of Hebrew more available',
					image: 'VAULT Wing folio ZP 538 .F9284, p. SOMETHING',
					src:'',
					metadata: '',
					creator: 'Johann Forster',
					textTitle: 'Dictionarium Hebraicum nouum',
					place: 'Basel, Switzerland',
					year: '1557',
					narrative: 'By making available definitive texts of the Bible in its original languages, polyglot scholars hoped to inspire other intelletuals to learn to use these languages on their own, so that the quality of Christian scholarship would grow. We can see this utilitarian function in the Newberry’s copy of the Complutensian, which shows how one early user tried to learn Hebrew. To do so, this user may have made use of a Latin-Hebrew dictionary such as the one by the scholar Johann Forster, who proudly claimed that his dictionary was solely on biblical sources, which the Complutensian provided in abundance.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=182836',
					otherAuthor: 'Bell, Dean Phillip.',
					otherTitle: 'Jews in the Early Modern World.',
					otherBib: 'New York: Rowman & Littlefield, 2008, 227-230.',
				},
				{
					id: 'cto3',
					type: 'Hebrew/Targum Root Words',
					category: 'tools',
					title: 'Interpretive Editions',
					subtitle: 'Polyglot editors interpret Hebrew before printing it',
					image: 'Wing ZP 539 G 94 sig b2r b1v',
					src: '',
					metadata: '',
					creator: 'Rabbi David Kimhi',
					textTitle: 'Liber Michlol',
					place: 'Paris',
					year: '1540',
					narrative: 'Classical Hebrew is composed of only consonants in its written form; readers could decide which vowels to supply when reading it, which could dramatically alter the meaning of the word. This forced editors to make decisions about how certain words could be interpreted, especially when they were compared with the Latin or Greek versions. Scholars did this by relying on Hebrew grammars, which offered guidance on how particular words ought to be pronounced. The Complutensian scholars relied especially on the work of Rabbi David Kimhi, an influential medieval grammarian whose work remained popular in the early modern period, as evidenced by the printed example shown here. ',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=483893',
					otherAuthor: 'Reuchlin, Johann.',
					otherTitle: 'De accentibus et orthographia linguae Hebraicae.',
					otherBib: 'Haguenau, 1518. VAULT Case PJ4581 .R4 1518',
				},
				],
			other: '',
		},

antwerp: {
	fullName: 'Plantin Polyglot (New Testament) – Open to Acts 2',
		sources: [
					{
						id: 'as1',
						type: 'Syriac Text',
						category: 'sources',
						title: 'The Syriac Bible',
						subtitle: 'Polyglot scholars seek out manuscripts other Near Eastern Christians',
						image: 'VAULT Hebrew MS 25, ff. SOMETHING',
						src:'',
						metadata: '',
						creator: 'Syriac Gospel Lectionary',
						place: '',
						year: '13th-15th century',
						narrative: 'i.	As these projects developed, people wanted more and more languages in order to help teach the “backward” Christians in the Near east. To do that, they needed manuscripts to come to them. ii.	Just talk about the Manuscript, I suppose. It is pretty fascinating. Give a bit of background on Syriac itself; a language used by some of the earliest Christians, who needed their own Bible.',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=844229',
					},
					{
						id: 'as2',
						type: 'Greek Text',
						category: 'sources',
						title: 'Greek Manuscripts',
						subtitle: 'Polyglot editors reveal the Greek New Testament',
						image: 'VAULT Greek MS 2, ff. 1v-2',
						src:'',
						metadata: '',
						creator: 'Gospels',
						textTitle: '',
						place: '',
						year: '12th century',
						narrative: 'Knowing Greek i.	Definitely use the reference to humanism, but point out how it was crucial for these guys to get manuscripts in Greek in order to do their work. More people knew about it, but you still had to go with the manuscripts ii.	Talk about collecting Greek Manuscripts; Complutense scholars got theirs from the Vatican…we think. Find out where others got theirs…',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=160179',
					},
					{
						id: 'as3',
						type: 'Greek Text (could be anything here)',
						category: 'sources',
						title: 'Acquiring Manuscripts',
						subtitle: 'Polyglot editors depend on merchants and diplomats to acquire the sources, they need.',
						image: 'Case G 601 .137, Title Page',
						src:'',
						metadata: '',
						creator: 'Ogier Ghislan de Busbecq',
						textTitle: 'The four epistles of A.G. Busbequius, concerning his embassy into Turkey.',
						place: 'London',
						time: '1694',
						narrative: 'i.	Now get to the money. People couldn’t do this without significant help, especially diplomats, scholars, and other people going into the Ottoman Empire and acquiring these manuscripts. Mention that this gets easier as the polyglot age goes on, as relations increase. ii.	Talk about Busbecq, who he is, and how he loved to go purchase manuscripts, especially Greek ones.',
						link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=269378',
					},
				],
				translations: [
				{
					id: 'at1',
					type: 'Greek and Latin Text',
					category: 'translations',
					title: 'The Polyglot Effect',
					subtitle: 'Printers place the entire Word of God before readers',
					image: 'Bonaparte 1928, Sig. A3 verso – A4',
					src:'',
					metadata: '',
					creator: 'Hieronymus Megiser',
					textTitle: 'Specimen quinquaginta diversarum atque inter se differentium linguarum, & dialectorum',
					place: 'Frankfurt am Main, Germany',
					year: '1603',
					narrative: 'Talk about the reason why polyglotters wanted these languages together; it was to undo the Tower of Babel. So showing them next to each other was probably a good thing. Things just got crazier as the polyglots went on, all the way up to 9 by the time we get to London. Talk about the history of this text, mention the languages that do not appear in the example, but the idea is that it’s the same text being shown all the time.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=666622',
				},
				{
					id: 'at2',
					type: 'Latin Vulgate',
					category: 'translations',
					title: 'Royal Patronage',
					subtitle: 'Polyglots as signs of political power',
					image: 'Wing oversize ZP 5465 .P7013, frontispiece',
					src:'',
					metadata: '',
					creator: 'Artist? – Ask Walter Melion',
					textTitle: '',
					place: 'Antwerp, Belgium',
					year: '1571',
					narrative: 'i.	We should be talking about patronage somewhere, and we could use that spectacular frontispiece of Hispania from this edition to show Philip II’s involvement in the project as a way of contributing to the Counter Reform. This is where Reed’s comment about “the Counter-Reformation in folio” should come in. ii.	We could also mention Plantin’s political and economic motivations here, or the fact that the majority of the scholars who worked on the project were actually Protestants.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=234961',
					},
					{
						id: 'at3',
						type: 'Hebrew Text',
						category: 'translations',
						title: 'Transliterating New Languages',
						subtitle: 'Scholars use Hebrew to unlock other Near Eastern languages',
						image: 'Wing ZP 556 .Z61',
						src:'',
						metadata: '',
						creator: 'Johann Widmanstetter, ed.',
						textTitle: 'Syriacae lingvae Iesv Christo, eivsque Matri Virgini atq; Iudaeis omnibus, Christianae redemptionis Euangelicaeq́…',
						place: 'Vienna',
						year: '1555',
						narrative: 'i.	Talk about how bringing in these new languages could be a problem, because nobody really knew how to read them. Polyglots were thus an opportunity to teach people these new languages. ii.	Discuss this text, which was the first Syriac Bible, but came with no translation, so no one could read it. The Antwerp scholars transliterated it into Hebrew, which was an improvement.',
						link: '',
					},
				],
				tools: [
				{
					id: 'ato1',
					type: 'Syriac Translation',
					category: 'tools',
					title: 'Philology and Near Eastern Studies',
					subtitle: 'Polyglots open up new forms of inquiry using Near Eastern languages',
					image: 'Case folio F 017 .788, Title Page',
					src:'',
					metadata: '',
					creator: 'Joseph Scaliger',
					textTitle: 'De emendatione temporum',
					place: 'Paris, France',
					year: '1583',
					narrative: 'i.	Another example of what this information produced by the polyglots helped make possible: the historical and philological study of Near Eastern cultures. Other scholars and humanists took the knowledge of languages etc. and used them to do other kinds of work. ii.	Talk about Scaliger and what he tries to do with this work, figure out how far back history goes and how to measure time, make clear the connection between his work and the Syriac in the polyglot.',
					link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=656475',
				},
				],
			other: '',
		},

london: {
		fullName: 'London Polyglot – Open to Proverbs 1',
		sources: [
			{
				id: 'ls1',
				type: 'Hebrew Text',
				category: 'sources',
				title: '',
				subtitle: '',
				image: 'no image',
				src: '',
				metadata:'',
				creator: '',
				textTitle: '',
				place: '',
				time: '',
				narrative: 'Founding letter types: Though the Hebrew is the “least good” of the types, we should mention here that these things often had to be made from scratch. London in particular was probably the work of multiple artists (see Reed, p. 163), so you can talk about that.',
				link:'',
			},
			{
				id: 'ls2',
				type: 'Vulgate Text',
				category: 'sources',
				title: '',
				subtitle: '',
				image: 'James Ussher, The reduction of episcopacie unto the form of synodical government,received in the ancient church',
				src:'',
				metadata: '',
				creator: 'James Ussher',
				textTitle: 'The reduction of episcopacie unto the form of synodical government,received in the ancient church',
				place: 'London, England',
				year: '',
				narrative: 'State Support: Describe how many people were still concerned with the possible damage done to the Vulgate, getting people involved in supporting the project was key. Describe Ussher, and his key role in getting London off the ground. Compare this to other important religious figures who supported polyglot projects in order to defend them from heresy accusations.',
				link: '',
			},
		],
		translations: [
			{
				id: 'lt1',
				type: 'Septuagint Text',
				category: 'translations',
				title: 'Matching Prints',
				subtitle: 'Printers rise to the challenge of presenting the same text ICK.',
				image: 'Case oversize C 211 .657, v. 3, pp. 118-119',
				src:'',
				metadata: '',
				creator: '',
				textTitle: 'Biblia sacra polyglotta',
				place: 'London, England',
				year: '1657',
				narrative: 'This is where we should make the point about how the printers themselves were involved in this activity; the fact that every passage here shows the exact same amount of text is quite remarkable, and fits into the idea of showing them the Word.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=236649',
			},
		],
		tools: [
			{
				id: 'lto1',
				type: 'Targum Text',
				category: 'tools',
				title: 'Supporting Oriental Studies',
				subtitle: 'Polyglots lead to creation of other linguistic material',
				image: 'Case oversize X 442 .15, sig. A',
				src:'',
				metadata: '',
				creator: 'Edmund Castell',
				textTitle: 'Lexicon heptaglotton',
				place: 'London, England',
				year: '1669',
				narrative: 'Talk more about Oriental Studies, with specific reference to learning how to read, speak, and write in these other Near Eastern languages. Explain this text, a giant dictionary for all seven of the languages used in the London polyglot, which was made in connection with this work.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=287925',
			},
			{
				id: 'lto2',
				type: 'Targum Translation',
				category: 'tools',
				title: 'Preparing the Way for the Polyglot',
				subtitle: 'Scholars create texts to help others use polyglots',
				image: 'Case X 3 .44, p.',
				src:'',
				metadata: '',
				creator: 'Brian Walton',
				textTitle: 'Introductio ad Lectionem Linguarum Orientalium',
				place: 'London, England',
				year: '1655',
				narrative: 'Oriental Studies, Similar to the Lexicon, but with more of an emphasis on communication. Discuss how these projects were meant to help clear up the unorthodoxies in the Christian East, which required written and oral communication. Talk about this text, and focus on how it was printed in preparation for the polyglot, which becomes a kind of master textbook text.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=764078',
			},
			{
				id: 'lto3',
				type: 'Arabic Text',
				category: 'tools',
				title: 'Arabic Studies',
				subtitle: 'Polyglots stimulate interest in Arabic materials',
				image: 'Wing ZP 535 .M4677, pp. 60-61',
				src:'',
				metadata: '',
				creator: '',
				textTitle: 'Alphabetum arabicum',
				place: 'Rome, Italy',
				year: '1592',
				narrative: 'Talk about the growing importance of Arabic studies, mention how London polyglot began with founding of Arabic chair at Oxford. Explain what kind of text this is, point out the Medici press’s focus on conversion and Arabic materials, which the British would have used.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=193340',
			},
			{
				id: 'lto4',
				type: 'Syriac Translation',
				category: 'tools',
				title: 'Preaching from the Polyglot',
				subtitle: 'Polyglots support preachers by providing context for the Bible',
				image: 'C 9911 .0755, sig. B verso',
				src:'',
				metadata: '',
				creator: 'Shute Barrington',
				textTitle: 'A sermon preached before the Lords Spiritual and Temporal in the Abbey Church of Westminster on Thursday, January 30, 1772',
				place: 'London, England',
				year: '1772',
				narrative: 'Talk about how these books were used for preaching; preachers in this period wanted to have the best version of the text to be able to preach the Word effectively to their congregations. Explain how this sermon was produced by using the Newberry’s copy of the London Polyglot, and how this image points to this very verse. Also point out that Barrington owned our copy of the Lexicon heptaglotton.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=217355',
			},
			{
				id: 'lto5',
				type: 'Arabic Translation',
				category: 'tools',
				title: 'Conversion and Education',
				subtitle: 'Polyglots pave the way for converting and education Near Eastern Christians',
				image: 'Wing folio ZP 845 .H6905, Proverbs 1',
				src:'',
				metadata: '',
				creator: '',
				textTitle: 'The Holy Bible, containing the Old and New Testaments, in the Arabic language.',
				place: 'Newcastle-upon-Tyne, England',
				year: '1811',
				narrative: 'Bibles Beget Bibles: Talk about conversion here, remind people of how the polyglots were supposed to help get to the Christians in the East. Talk about this particular Bible, note that the Arabic text was based on the London polyglot, and was also produced under the auspices of Shute Barrington.',
				link: 'https://i-share.carli.illinois.edu/nby/cgi-bin/Pwebrecon.cgi?DB=local&v1=1&BBRecID=236660',
			}
		],
			other: '',
	},
};
